name: Setup Cloud Schedulers

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'configs/default.json'
      - 'scripts/setup_schedulers.sh'
      - '.github/workflows/deploy-schedulers.yml'

env:
  PROJECT_ID: insightsprod
  REGION: us-central1
  TOPIC_NAME: boxout-sftp-export-triggers
  SERVICE_ACCOUNT: boxout-sftp-export@insightsprod.iam.gserviceaccount.com

jobs:
  setup-schedulers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up jq
      uses: dcarbone/install-jq-action@v2.0.1
      
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        
    - name: Setup Cloud Schedulers
      run: |
        # Read export configs from JSON file
        EXPORTS=$(cat configs/default.json | jq -r '.exports | keys[]')
        
        # Create a scheduler for each export
        for EXPORT_NAME in $EXPORTS; do
          SCHEDULER_ID="boxout-sftp-export-${EXPORT_NAME}"
          SCHEDULER_DESC="Daily SFTP export for ${EXPORT_NAME} at 1:00 PM IST"
          SCHEDULE="0 13 * * *"  # 1:00 PM in IST timezone
          
          echo "📅 Setting up scheduler for ${EXPORT_NAME} to run at 1:00 PM IST..."
          
          # Delete the scheduler if it already exists
          if gcloud scheduler jobs describe ${SCHEDULER_ID} --location=${{ env.REGION }} &> /dev/null; then
            gcloud scheduler jobs delete ${SCHEDULER_ID} --location=${{ env.REGION }} --quiet
          fi
          
          # Create the Cloud Scheduler job
          gcloud scheduler jobs create pubsub ${SCHEDULER_ID} \
            --location=${{ env.REGION }} \
            --schedule="${SCHEDULE}" \
            --topic=${{ env.TOPIC_NAME }} \
            --message-body="{\"export_name\":\"${EXPORT_NAME}\"}" \
            --description="${SCHEDULER_DESC}" \
            --time-zone="Asia/Kolkata" \
            --attributes="origin=scheduler"
            
          echo "✅ Scheduler created for ${EXPORT_NAME}"
        done
        
    - name: Completion Message
      run: echo "🎉 All schedulers have been set up successfully!"
